// Generated by models/levi/src/levi.py
// Units: millimeters
outer_length = 120;
outer_width = 80;
outer_height = 50;
wall_thickness = 2;
cut_epsilon = 0.01;

module levi_box() {
  difference() {
    cube([outer_length, outer_width, outer_height], center = false);
    translate([wall_thickness, wall_thickness, wall_thickness])
      cube([
        outer_length - wall_thickness * 2,
        outer_width - wall_thickness * 2,
        outer_height - wall_thickness + cut_epsilon
      ], center = false);
  }
}

levi_box();
