#!/usr/bin/env python3
"""Generate a PythonSCAD/OpenSCAD starter model for the Levi box."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


MODEL_NAME = "levi_box"
WALL_THICKNESS_MM = 2.0
OUTER_LENGTH_MM = 120.0
OUTER_WIDTH_MM = 80.0
OUTER_HEIGHT_MM = 50.0
CUT_EPSILON_MM = 0.01


def scad_number(value: float) -> str:
    return f"{value:.6g}"


@dataclass(frozen=True)
class HollowBox:
    length: float = OUTER_LENGTH_MM
    width: float = OUTER_WIDTH_MM
    height: float = OUTER_HEIGHT_MM
    wall: float = WALL_THICKNESS_MM

    def validate(self) -> None:
        if self.wall <= 0:
            raise ValueError("wall thickness must be positive")
        if self.length <= self.wall * 2:
            raise ValueError("length must be greater than twice the wall thickness")
        if self.width <= self.wall * 2:
            raise ValueError("width must be greater than twice the wall thickness")
        if self.height <= self.wall:
            raise ValueError("height must be greater than the wall thickness")

    def to_scad(self) -> str:
        self.validate()
        return f"""module {MODEL_NAME}() {{
  difference() {{
    cube([outer_length, outer_width, outer_height], center = false);
    translate([wall_thickness, wall_thickness, wall_thickness])
      cube([
        outer_length - wall_thickness * 2,
        outer_width - wall_thickness * 2,
        outer_height - wall_thickness + cut_epsilon
      ], center = false);
  }}
}}

{MODEL_NAME}();
"""


def build_scad(box: HollowBox) -> str:
    return "\n".join(
        [
            "// Generated by models/levi/src/levi.py",
            "// Units: millimeters",
            f"outer_length = {scad_number(box.length)};",
            f"outer_width = {scad_number(box.width)};",
            f"outer_height = {scad_number(box.height)};",
            f"wall_thickness = {scad_number(box.wall)};",
            f"cut_epsilon = {scad_number(CUT_EPSILON_MM)};",
            "",
            box.to_scad(),
        ]
    )


def write_model(output: Path, box: HollowBox) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_scad(box), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--length", type=float, default=OUTER_LENGTH_MM)
    parser.add_argument("--width", type=float, default=OUTER_WIDTH_MM)
    parser.add_argument("--height", type=float, default=OUTER_HEIGHT_MM)
    parser.add_argument("--wall", type=float, default=WALL_THICKNESS_MM)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "outputs" / f"{MODEL_NAME}.scad",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    box = HollowBox(
        length=args.length,
        width=args.width,
        height=args.height,
        wall=args.wall,
    )
    write_model(args.output, box)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
